x-dbpath: &p # server as value holder for compose file
  /db

x-logpath: &l
  /log

services:
  chainservice:
    build: ./chainService
    configs:
      - source: chainService_config
        target: /configs/config.yaml
    volumes:
      - type: volume
        source: db-path
        target: *p
      - type: bind
        source: ./log/
        target: *l
    environment:
      DB_PATH: *p
      LOG_PATH: *l
      LOG_ENC: json
      MODE: dev

  signingservice:
    build: ./signingService
    configs:
      - source: signingService_config
        target: /configs/config.yaml
    ports:
      - 6579: 6579

# todo: add collector service image
  collectorService:
    build: "image"
    ports:
      - 8080: 8080

configs:
  chainService_config:
    file: ./chainService/config.yaml
  signingService_config:
    file: ./signingService/config.yaml
volumes:
  db-path:
  log-path: