x-dbpath: &p # server as value holder for compose file
  /db

x-logpath: &l
  /log

services:
  chainservice:
    depends_on:
      - signingservice
    build: ./chainService
    volumes:
      - type: volume
        source: db-path
        target: *p
      - type: volume
        source: log-path
        target: *l      
      - type: bind
        source: ./chainService/config.yaml
        target: /configs/config.yaml
      - ./chainService/ca.cer:/configs/ca.cer
      - ./chainService/attestor1.key:/configs/attestor1.key
      - ./chainService/attestor1.crt:/configs/attestor1.crt
    environment:
      DB_PATH: *p
      LOG_PATH: *l
      LOG_ENC: json
      MODE: dev
      CLEAN_START: false
  signingservice:
    build:
      context: .
      dockerfile: ./signingService/Dockerfile
    volumes:
      - ./signingService/config.yaml:/configs/config.yaml
      - ./signingService/keys.yaml:/configs/keys.yaml
    ports:
      - 8080:8080

volumes:
  db-path:
  log-path:
