server:
  http_listen_port: 9080
  grpc_listen_port: 0

positions:
  filename: /tmp/positions.yaml

clients:
  - url: https://prometheus-testnet.venture23.xyz:3101/loki/api/v1/push
    batchwait: 2m

scrape_configs:
  - job_name: system
    static_configs:
      - targets:
          - localhost
        labels:
          job: verulink_logs
          __path__: /var/log/verulink*.log