#cloud-config
# Create a group
groups:
  - ubuntu

# Create users, in addition to the users provided by default
users:
  - default
  - name: ubuntu
    gecos: ubuntu
    shell: /bin/bash
    primary_group: hashicorp
    sudo: ALL=(ALL) NOPASSWD:ALL
    groups: users, admin
    lock_passwd: false
    ssh_authorized_keys:
      - "ssh-rsa AAAAB3NzaC1yc2EAAAADAQABAAABgQC4jvVJ5e6SdlkAExdY8emz/pEpL4vdPKD7Ml/8iH/Ap9f/k99F4dm/8K9Gc+7MmpGZQVjQeZrUKWn+KD6vUJ4waF3/fr952ukli5MFyi3l00OK0fG7VNtE6WNZzjzXe1f+7JZPOhGVT5ALBMmTK/mdF3qpa4SWQ24aJlEJynTkEHIkPKaQf7F4cvACrgs83NauS8nib3WkJMeh6zcub5B94FSvWrKw85h1fSX1F5XKeqt81JiEpSBBYrfDF6Hi7bIifqU4UIadjhH8j0NkbYjCvmF0v9gSB4Ab5f7O020i/kssLKOBKLwTRgiAR4zqzpQpeupLLEHlWzZlpbudkEKm3cQfNEQ9fOM17wCN3SRZ9HWzogCJKBv4CiBIPInMNa+8s5yQDlMjoC/gz7vUrpS6X5WH3jaz7XGsWSjMYYJRjYuUrlAOHgQQO28TQnnrVJNktpkWFjdhCTk9HBQPekq8+mJxl0jDNao4BvSqPC6N76IlKZFzK9KqiT2Xqz3Oegc= logpoint@Logpoints-MacBook-Pro.local" # an SSH public key that is authorized
                      # to connect to this account
# Run a few commands (update apt's repo indexes and install curl)
runcmd:
  - sudo apt-get update
  - sudo apt install curl -q -y
  - echo "Done"