---
chains: 
  - name: ethereum
    token_service_contract_address: 0x5554f1660e1464a86E9155374ea33b0Ab7b890Bd
    usdc_contract_address: 0xD99e898842c566be038bf898b3e406f028a031E0
    bridge_contract_address: 0xB83766b28bE2Cf6Fb28Cd055beFB55fdc68CfC9C
    node_url: http://localhost:3001
    wallet_path: /home/aanya/.ethereum/keystore/UTC--2024-07-09T05-45-45.482980559Z--2ca02613ce51b3ed6930e89c63c66219f8e41121
    wallet_address: 0x2ca02613ce51b3ed6930e89c63c66219f8e41121
  - name: aleo
    token_service_contract_address: token_service_v0001.aleo
    usdc_contract_address: wusdc_token_v0001.aleo
    bridge_contract_address: token_bridge_v0001.aleo
    node_url: http://localhost|testnet
    wallet_path: APrivateKey1zkp4RfjRhZ9apYoF75EsPhEVKJijDoRTxeZRk7Y9C7bWt4B
    wallet_address: wallet_address
collector_service_uri: https://aleomtls.ibriz.ai
write_config_path: ../chainService/config.yaml
