x-dbpath: &p # server as value holder for compose file
  /db

x-logpath: &l
  /log

services:
  attestor:
    build: .
    configs:
      - source: attestor_config
        target: config.yaml
    volumes:
      - type: volume
        source: db-path
        target: *p
      - type: bind
        source: ./log/
        target: *l
    environment:
      DB_PATH: *p
      LOG_PATH: *l
      LOG_ENC: json

configs:
  attestor_config:
    file: ./config.yaml

volumes:
  db-path:
  log-path: