x-dbpath: &p # server as value holder for compose file
  /db

x-logpath: &l
  /log

version: '3'
services:
  chainservice:
    build: .
    volumes:
      - type: volume
        source: db-dir
        target: *p
      - type: volume
        source: log-dir
        target: *l
      - type: bind
        source: ./config.yaml
        target: /configs/config.yaml
    environment:
      DB_PATH: *p
      LOG_PATH: *l
      LOG_ENC: json
      MODE: dev
    networks:
      my-attestor-network:

volumes:
  db-dir:
  log-dir:

networks:
  my-attestor-network:
    external: true