---
chains:
- name: aleo
  chain_id: 2
  bridge_contract: bridge.aleo
  node_url: http://52.91.48.169|testnet3
  start_from: 0
  wait_time: 24h # 24 hours
- name: ethereum
  chain_id: 1
  bridge_contract: '0x2Ad6EB85f5Cf1dca10Bc11C31BE923F24adFa758'
  node_url: https://rpc.sepolia.org
  start_from: 0
  wait_time: 24h # 24 hours
db_path: db
log:
  encoding: console
  output_path: relays.log
