---
chains:
- name: aleo
  chain_id: 2
  bridge_contract: bridge.aleo
  node_url: http://52.91.48.169|testnet3
  sequence_num_start:
    ethereum: 0
    # solana: 23 # solana is just for config example
  wait_time: 24h
- name: ethereum
  chain_id: 1
  bridge_contract: '0x2Ad6EB85f5Cf1dca10Bc11C31BE923F24adFa758'
  node_url: https://rpc.sepolia.org
  start_height: 1
  wait_time: 24h
db_path: db
consume_packet_workers: 10 # Default is 10
log:
  encoding: console
  output_path: relays.log
mode: dev # dev/prod
