---
name: prod_attestor_verulink_<yourCompanyIdentifier>
version: 1.0.0
chains:
- name: aleo
  chain_id: 6694886634401
  wallet_address: aleo1jelsappz5y0cy54cdqukc6xyvz45f35t99mgmlmu3uu7pndvayyqmnx5za # wallet indentifier
  bridge_contract: vlink_token_bridge_v1.aleo
  node_url: https://api.explorer.aleo.org/v1|testnet
  sequence_num_start:
    ethereum: 1
    # solana: 23 # solana is just for config example
  pkt_validity_wait_dur: 86400s
  finality_height: 28800
  retry_packet_wait_dur: 30m
  prune_base_seq_num_wait_dur: 30m
  average_block_gen_dur: 3s
  dest_chains:
    - ethereum

- name: ethereum
  chain_id: 27234042785
  wallet_address: 0x684C68bE1b58f61a33888E0eE3EA63f021d8CB0a
  bridge_contract: 
  node_url: 
  start_height: 
  finality_height: 7200
  filter_topic: 0x23b9e965d90a00cd3ad31e46b58592d41203f5789805c086b955e34ecd462eb9
  feed_pkt_wait_dur: 15m
  pkt_validity_wait_dur: 86400s
  retry_packet_wait_dur: 30m
  prune_base_seq_num_wait_dur: 30m
  dest_chains:
    - aleo

check_health_service : 1m
db_dir: /path/to/db/dir
consume_packet_workers: 10 # Default is 10
log:
  encoding: console
  output_dir: /path/to/log/dir
mode: prod # dev/prod

signing_service:
  host: signingservice
  port: 8080
  endpoint: "/sign"
  scheme: "http" # https, http, rpc, etc.
  username: "<signing_service_username>"
  password: "<signing_service_password>"
  health_end_point: "/health"
collector_service:
  uri : https://dbservice-mainnet-mtls.verulink.com
  # Within collector_wait_dur, collector-service will try to collect all unconfirmed packets iteratively
  collector_wait_dur: 1h
  ca_certificate: /configs/.mtls/ca.cer
  attestor_certificate: /configs/.mtls/attestor1.crt
  attestor_key: /configs/.mtls/attestor1.key

metrics:
  host: https://pushgateway-aleomtls.venture23.xyz
  job_name: dev-push-gateway