---
name: <releaseIdentifier>_attestor_verulink_<yourCompanyIdentifier>
version: 1.0.2
chains:
- name: aleo
  chain_id: 6694886634401
  wallet_address: <your_aleo_wallet_address> # wallet indentifier
  bridge_contract: vlink_token_service_v2.aleo
  node_url: https://api.explorer.provable.com/v1|testnet
  sequence_num_start:
    ethereum: 1
    # solana: 23 # solana is just for config example
  pkt_validity_wait_dur: 300s
  finality_height: 100
  retry_packet_wait_dur: 1m
  prune_base_seq_num_wait_dur: 30m
  average_block_gen_dur: 3s
  dest_chains:
    - ethereum

- name: ethereum
  chain_id: 27234042785
  wallet_address: <your_ethereum_wallet_address>
  bridge_contract: 0x15E53390EaF022421E0B27048E0C11776081f75d
  node_url: https://rpc2.sepolia.org
  start_height: 6676394
  finality_height: 25
  filter_topic: 0x23b9e965d90a00cd3ad31e46b58592d41203f5789805c086b955e34ecd462eb9
  feed_pkt_wait_dur: 30s
  pkt_validity_wait_dur: 240s
  retry_packet_wait_dur: 1m
  prune_base_seq_num_wait_dur: 30m
  dest_chains:
    - aleo

check_health_service : 1m
db_dir: /path/to/db/dir
consume_packet_workers: 10 # Default is 10
log:
  encoding: console
  output_dir: /path/to/log/dir
mode: prod # dev/prod

signing_service:
  host: signingservice
  port: 8080
  endpoint: "/sign"
  scheme: "http" # https, http, rpc, etc.
  username: "username"
  password: "password"
  health_end_point: "/health"
collector_service:
  uri : <collector_service_url>
  # Within collector_wait_dur, collector-service will try to collect all unconfirmed packets iteratively
  collector_wait_dur: 1h
  ca_certificate: /configs/.mtls/ca.cer
  attestor_certificate: /configs/.mtls/attestor1.crt
  attestor_key: /configs/.mtls/attestor1.key

metrics:
  host: <prometheus_pushgateway_url>
  job_name: prod-push-gateway
