---
chains:
- name: aleo
  chain_id: 2
  wallet_address: "address" # wallet indentifier
  bridge_contract: bridge.aleo
  node_url: http://52.91.48.169|testnet3
  sequence_num_start:
    ethereum: 0
    # solana: 23 # solana is just for config example
  wait_time: 24h
  retry_packet_wait_dur: 12h
  prune_base_seq_num_wait_dur: 6h
- name: ethereum
  chain_id: 1
  wallet_address: "address"
  bridge_contract: '0x2Ad6EB85f5Cf1dca10Bc11C31BE923F24adFa758'
  node_url: https://rpc.sepolia.org
  start_height: 1
  wait_time: 24h
  filter_topic: '0x23b9e965d90a00cd3ad31e46b58592d41203f5789805c086b955e34ecd462eb9'
  retry_packet_wait_dur: 12h
  prune_base_seq_num_wait_dur: 6h
db_path: db
consume_packet_workers: 10 # Default is 10
log:
  encoding: console
  output_path: relays.log
mode: dev # dev/prod
signing_service:
  host: "host name"
  port: 6579
  endpoint: "/sign"
  scheme: "communication scheme" # https, http, rpc, etc.
  username: "user name"
  password: "password"
  ping_endpoint: "/ping"
collector_service:
  uri: https://collector.service.uri
  collector_wait_dur: 12h
