chains:
- name: aleo
  chain_id: 6694886634403
  wallet_address: aleo1zgyyxkjxadc4y7aks4rscmz6sq59wljrjckuwgrwsx034uxkkuyqmtjdw7 # wallet indentifier
  bridge_contract: token_bridge_v0002.aleo
  node_url: https://api.explorer.aleo.org/v1|testnet3
  sequence_num_start:
    ethereum: 1
    # solana: 23 # solana is just for config example
  pkt_validity_wait_dur: 1m
  finality_height: 1
  retry_packet_wait_dur: 1m
  prune_base_seq_num_wait_dur: 1m
  dest_chains:
    - ethereum

- name: ethereum
  chain_id: 28556963657430695
  wallet_address: 0x5Dc561633F195d44a530CdF0f288a409286797ff
  bridge_contract: 0xC89f5074765Ac2aF3E3b0D9C9fc6079895F02193
  node_url: https://rpc.sepolia.org
  start_height: 5281000
  finality_height: 64
  filter_topic: 0x23b9e965d90a00cd3ad31e46b58592d41203f5789805c086b955e34ecd462eb9
  feed_pkt_wait_dur: 2s
  pkt_validity_wait_dur: 2s
  retry_packet_wait_dur: 1m
  prune_base_seq_num_wait_dur: 1m
  dest_chains:
    - aleo

db_dir: /path/to/db/dir
consume_packet_workers: 10 # Default is 10
log:
  encoding: console
  output_dir: /path/to/log/dir
mode: dev # dev/prod

signing_service:
  host: signingservice
  port: 8080
  endpoint: "/sign"
  scheme: "http" # https, http, rpc, etc.
  username: "username"
  password: "password"

collector_service:
  uri: https://aleobridge-dbservice-develop.b08qlu4v33brq.us-east-1.cs.amazonlightsail.com/
  # Within collector_wait_dur, collector-service will try to collect all unconfirmed packets iteratively
  collector_wait_dur: 1h
