chains:
    - name: aleo
      chain_id: "2"
      bridge_contract: bridge.aleo
      node_url: http://node.url|testnet3
      wait_duration: 1m0s
      wallet_path: ""
      dest_chains:
        - "1"
      sequence_num_start:
        "1": 1
      start_height: 0
      filter_topic: ""
      retry_packet_wait_duration: 1m0s
      prune_base_seq_num_wait_duration: 1m0s
    - name: ethereum
      chain_id: "1"
      bridge_contract: 0x718721F8A5D3491357965190f5444Ef8B3D37553
      node_url: https://rpc.sepolia.org
      wait_duration: 1m0s
      wallet_path: ""
      dest_chains:
        - "2"
      sequence_num_start:
        "2": 1
      start_height: 100
      filter_topic: 0x23b9e965d90a00cd3ad31e46b58592d41203f5789805c086b955e34ecd462eb9
      retry_packet_wait_duration: 1m0s
      prune_base_seq_num_wait_duration: 1m0s
log:
    encoding: console
    output_dir: log
db_path: db
consume_packet_worker: 50
mode: dev
