name: 'Assert Branch Naming Convention'
on: pull_request

jobs:
  branch-naming-rules:
    runs-on: ubuntu-latest
    steps:
      - uses: deepakputhraya/action-branch-name@v1.0.0
        with:
          regex: '([a-z])+\/([a-z])+'
          allowed_prefixes: 'feature,stable,fix,test,ci,bugfix'
          ignore: master,develop,release
          min_length: 5
          max_length: 20
